#https://github.com/BnZel/course-material
language: node_js

node_js:
  - "10.9.0"

cache: npm

before_install:
  - ls -la
  - "npm config set spin false"
  - npm i -g now

install:
  - npm install

script:
  - npm run build
  - npm run test

notifications:
  slack: gbcdevopssquad:Tytm620BaZ1HHvXTYKcGwS3k
