#https://github.com/BnZel/course-material
language: node_js

node_js:
  - "10.9.0"

cache: npm

before_install:
  - ls -la
  - "npm config set spin false"
  - npm i -g now

install:
  - npm install
  - npm run build

script:
  - npm run test

deploy:
  provider: script
  script: bash scripts/deploy.sh
  skip_cleanup: true

env:
  - NOW_TOKEN=h9gxym8m8VEgYvU3pqqjzEWZ

notifications:
  slack: gbcdevopssquad:Tytm620BaZ1HHvXTYKcGwS3k
